name: Deploy to GitHub Pages (after smoke test)

# This workflow is triggered after the Smoke Test workflow completes successfully.
on:
  workflow_run:
    workflows:
      - "Smoke Test"
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: .        # The folder the action should deploy.
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}
