name: Smoke Test

on:
  push:
  pull_request:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Install http-server
        run: npm install -g http-server

      - name: Start static server
        run: |
          http-server -p 8000 &
          echo $! > server.pid

      - name: Wait for server
        run: npx wait-on http://localhost:8000

      - name: Run smoke test
        env:
          TEST_URL: http://localhost:8000
        run: npm run smoke

      - name: Stop server
        if: always()
        run: |
          if [ -f server.pid ]; then kill $(cat server.pid) || true; fi
